- CHANGELOG.md
- setup.py
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/config.py
- src/evergreen/stats.py
- src/evergreen/task_reliability.py
- tests/conftest.py
- tests/evergreen/data/task_reliability.json
- tests/evergreen/data/task_stats.json
- tests/evergreen/test_stats.py
- tests/evergreen/test_task_reliability.py
Added task-stats.
changed get_api to use api_server_host (for local testing).
reordered CONFIG_FILE_LOCATIONS so that ~/cli_bin is used first.
> Added task-reliability.

- CHANGELOG.md
- setup.cfg
- src/evergreen/__init__.py
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/util.py
- tests/conftest.py
- tests/evergreen/test_api.py
- tests/evergreen/test_util.py
I noticed we are doing this quite a bit. So it seems useful to put in this library.
> MAKE-997: add time-based iterators

- .evergreen.yml
- CHANGELOG.md
- README.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/base.py
- src/evergreen/build.py
- src/evergreen/commitqueue.py
- src/evergreen/config.py
- src/evergreen/distro.py
- src/evergreen/errors/exceptions.py
- src/evergreen/host.py
- src/evergreen/manifest.py
- src/evergreen/metrics/buildmetrics.py
- src/evergreen/metrics/versionmetrics.py
- src/evergreen/patch.py
- src/evergreen/performance_results.py
- src/evergreen/project.py
- src/evergreen/stats.py
- src/evergreen/task.py
- src/evergreen/task_reliability.py
- src/evergreen/tst.py
- src/evergreen/version.py
There was a request for python 3.6 support. The big thing we lose is some of the more advanced type support, but there are some workarounds for it.
> MAKE-1317: Add support for python 3.6

- CHANGELOG.md
- pyproject.toml
- src/evergreen/task.py
- tests/evergreen/test_task.py
This will also fix DAG-238 without any code changes in the bb repo.
> MAKE-1385 get_tests by task execution

- .evergreen.yml
- CHANGELOG.md
- README.md
- docs/source/conf.py
- docs/source/evergreen.errors.rst
- docs/source/evergreen.metrics.rst
- docs/source/evergreen.rst
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/modules.rst
- docs/source/sample_usage.rst
- poetry.lock
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/task.py
- src/evergreen/util.py
I mentioned in standup. I set up a documentation page for this project. 
Since this is the first PR, I've published the changes so you can see what they look like: https://evergreen-ci.github.io/evergreen.py/
> DAG-298: Add sphinx documentation

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- poetry.lock
- pyproject.toml
- setup.cfg
- src/evergreen/alias.py
- src/evergreen/api.py
- src/evergreen/base.py
- src/evergreen/build.py
- src/evergreen/cli/main.py
- src/evergreen/commitqueue.py
- src/evergreen/config.py
- src/evergreen/distro.py
- src/evergreen/errors/exceptions.py
- src/evergreen/host.py
- src/evergreen/manifest.py
- src/evergreen/metrics/buildmetrics.py
- src/evergreen/metrics/versionmetrics.py
- src/evergreen/patch.py
- src/evergreen/performance_results.py
- src/evergreen/project.py
- src/evergreen/stats.py
- src/evergreen/task.py
- src/evergreen/task_reliability.py
- src/evergreen/tst.py
- src/evergreen/util.py
- src/evergreen/version.py
- tests/evergreen/test_alias.py
Add isort
Add bugbear
Add pre-commit
> DAG-472: Add additional static analysis checks

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/util.py
- src/evergreen/version.py
- tests/evergreen/test_api.py
- tests/evergreen/test_util.py
- tests/evergreen/test_version.py
> DAG-479: Enable users to access type information

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#list-tasks-by-project-and-commit
> Add support for /projects/{project_id}/revisions/{commit_hash}/tasks

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- src/evergreen/metrics/buildmetrics.py
- src/evergreen/metrics/versionmetrics.py
- src/evergreen/task.py
- tests/evergreen/data/task.json
- tests/evergreen/metrics/test_buildmetrics.py
- tests/evergreen/metrics/test_versionmetrics.py
- tests/evergreen/test_task.py
[DAG-723](https://jira.mongodb.org/browse/DAG-723)
> DAG-723: Remove 'estimated_cost' field from evergreen API

- .gitignore
- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/resource_type_permissions.py
- tests/conftest.py
- tests/evergreen/cli/test_main.py
- tests/evergreen/data/user_permissions.json
- tests/evergreen/test_api.py
* Implements these APIs -
** https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#give-permissions-to-user
** https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-user-permissions
* Adds a CLI command to get user permissions
> Add support to get and set user permissions

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/resource_type_permissions.py
- tests/evergreen/cli/test_main.py
- tests/evergreen/test_api.py
* Implement DELETE /users/<user_id>/permissions
* Add missing test for the give_permissions_to_user API method.
* Add CLI command to delete user permissions.
> Add support to delete user permissions

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
I needed this functionality for some maintenance. Thanks for this project!
> EVG-15912: added host_by_id

- CHANGELOG.md
- README.md
- pyproject.toml
Added some clarification for configuring the Evergreen CLI to work in this package.
> Update README to explain how to use Evergreen CLI.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
Added revision_start and revision_end to versions_by_project
> Add revision_start and revision_end to versions_by_project

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/task.py
- tests/evergreen/test_api.py
Adding a few missing things I need to the library.
> SERVER-81209 Add execution param to task_by_id

- CHANGELOG.md
- pyproject.toml
- src/evergreen/version.py
related to [DAG-2879](https://jira.mongodb.org/browse/DAG-2879)
> DAG-2879 added empty value for build_variants_map

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/patch.py
- tests/evergreen/test_api.py
Added ID to the PatchCreationDetails model because I need it for a ticket I'm working on.
> DEVPROD-3201 Add id to PatchCreationDetails model.

- CHANGELOG.md
- README.md
- pyproject.toml
https://jira.mongodb.org/browse/DEVPROD-343
> DEVPROD-343: switch to merge queue

- pyproject.toml
I didn't do this as part of the initial PR.
> DEVPROD-6266: Bump version for deployment.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
[DEVPROD-16137](https://jira.mongodb.org/browse/DEVPROD-16137)
Add `strategies` parameter for test selection endpoint.
> DEVPROD-16137: add strategies parameter to select tests endpoint

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
Fixed up the logging so we have stdout and stderr in case of a failure.
> DEVPROD-16981 Add additional logging when cloning patches.

- .evergreen.yml
https://jira.mongodb.org/browse/DEVPROD-16226
Testing:
> DEVPROD-16226: Generate a token so read/write operations can work
