evergreen-ci/evergreen.py

- CHANGELOG.md
- src/evergreen/__init__.py
- src/evergreen/build.py
- src/evergreen/performance_results.py
- src/evergreen/task.py
- src/evergreen/version.py
- tests/evergreen/test_performance_results.py
I'm keeping the 'start' and 'end' attributes, but not converting them to datetimes. That way if someone wants them, they can get them. 
Also, added `__repr__` functions to a bunch of objects to make logs nicer. 
And a bit of cleanup.
> MAKE-1022: Do not convert start/end to datetimes in performance results

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
This is technically a breaking change, but I don't think we are relying on it anywhere.
> MAKE-1231: Rethrow exceptions after failed retry

- CHANGELOG.md
- README.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/config.py
- tests/evergreen/test_api.py
The projects/id/recent_versions endpoint does not return json matching the schema expected by the Version class. 
For now, return the parsed json instead. 
Minor tweaks, and a utility function added for laptop-based use.
> Fix response from /recent_versions endpoint

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/conftest.py
- tests/evergreen/test_api.py
- POST [/tasks/{task_id}/restart](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#restart-a-task)
- POST [/tasks/{task_id}/abort](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#abort-a-task)
- PATCH [/tasks/{task_id}](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#change-a-tasks-execution-status)
- POST [/patches/{patch_id}/configure](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#configureschedule-a-patch)
Refactored `_call_api` to be used for all requests -- instead of only GET. Another option would be to rename the method to reflect that it's only used for GET and add separate methods for POST & PATCH, however this would involve the same amount of line changes.
> Add endpoints for updating patches & tasks

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#id58
Add support for getting a single test by it's test file name and associated task_id
> Add support for getting a test by task and test file

- CHANGELOG.md
- pyproject.toml
While using latest evergreen.py with python 3.9.0, I'm getting following warnings:
```
=============================== warnings summary ===============================
../../usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py:42
/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py:42: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
def call(self, fn, *args, **kwargs):
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
This issue is already fixed in tenacity 6.1.0 https://github.com/jd/tenacity/commit/66de0110844a742b820ab6c1f29edb19ed2e5908
I have updated pyproject.toml to allow `tenacity >= 5` so that I can get rid of above mentioned warning with python 3.9.0
> upgrade tenacity version requirement

- CHANGELOG.md
- pyproject.toml
- src/evergreen/cli/main.py
Adds two evg-api commands:
"manifest" gets the manifest for a project and commit hash.
"get-module-commit" gets a module commit from a project and commit hash. E.g., get the "wtdevelop" commit for the "mongo" project like this:
```
> evg-api get-module-commit --project mongodb-mongo-master --commit 51bef6c2d9d035afed3735ea107d1e7b58392d93 --module wtdevelop
cf79d062ecdaa7509ca80c4a643268ee5303e915
```
This may be useful for developers in a git checkout hook to keep modules in sync with their main repo.
> Add CLI support for manifests and module hashes

- .evergreen.yml
- CHANGELOG.md
- pyproject.toml
- src/evergreen/cli/main.py
- tests/evergreen/cli/test_main.py
Added testing to the `evg-api` commands. Currently, the `main.py` file has 98% coverage.
I also, added a new task to test proper installation of `evg-api`.
> DAG-1210: Add tests for the evergreen.py command line app

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- tests/evergreen/cli/test_main.py
- tests/evergreen/test_api.py
* Adds support for the `give roles to user` API endpoint.
* Add a CLI command that will allow a user to do the same but we limit the interaction to grant one role at a time to keep it simple.
> Add support for  `give roles to user` API endpoint

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- tests/evergreen/cli/test_main.py
- tests/evergreen/test_api.py
* Add resource_id param to delete user permissions endpoint. 
** This was just added earlier today to evergreen core.
> Add resource_id param to delete user permissions endpoint

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- tests/evergreen/cli/test_main.py
- tests/evergreen/test_api.py
* Adds support for the `get users for role` endpoint - https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-users-for-role
> Add get users for role endpoint

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/task.py
- tests/evergreen/test_api.py
- tests/evergreen/test_task.py
Evergreen API returns just int value, e.g.:
https://evergreen.mongodb.com/rest/v2/tasks/mongodb_mongo_master_enterprise_rhel_80_64_bit_dynamic_required_jsCore_2330ce3962a1cbce03510d6cf8ccacc82e637c76_22_05_25_09_49_18/tests/count
```
2478
```
> DAG-1851 Add test count from task endpoint support

- CHANGELOG.md
- README.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/cli/main.py
- src/evergreen/patch.py
- tests/evergreen/test_api.py
These APIs are required for [DAG-2439](https://jira.mongodb.org/browse/DAG-2439?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true). You can see further discussion of these specific APIs in [EVG-19103](https://jira.mongodb.org/browse/EVG-19103).
This is the first of multiple PRs to enable this functionality. The subsequent PRs will be in signal-processing-service.
It's worth noting that the `patch-from-diff` command is unique in this repo because is not a REST API. It it's actually a CLI.
We could probably make the `patch-from-diff` API a little more flexible by not requiring all the params, but I don't think it's worth the time because it's really only being added for our specific usecase. 
Here are some example outputs from the CLI:
```bash
➜ …
```
> DAG-2439 Added APIs needed to create profiling enabled patches.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/task.py
- tests/evergreen/data/task.json
- tests/evergreen/test_task.py
Needed to add this field so we can add the attribute to the BFG collection, see [relevant code](https://github.com/10gen/build-baron-tools/blob/15debc0a0534da32d42102216ddffd4e70522439/src/bb/models/task_failure.py#L195) in BB Tools.
> DAG-2485 Add build_variant_display_name to Task.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/api_requests.py
- src/evergreen/task.py
- src/evergreen/task_annotations.py
- tests/evergreen/data/task_annotations.json
- tests/evergreen/test_api.py
- tests/evergreen/test_task_annotations.py
See [DAG-2538](https://jira.mongodb.org/browse/DAG-2538).
I followed the [evergreen docs](https://docs.devprod.prod.corp.mongodb.com/evergreen/Use-the-API/REST-V2-Usage#resources) to model the field.
I ran the module locally and verified the outputs:
```
>>> task.annotate(metadata_links=[MetadataLinkRequest(url="https://evergreen.mongodb.com", text="evergreen")])
>>> for annotation in task.get_task_annotation(): print(annotation.__dict__)
{
'json': {
... 
'task_id': 'mongodb_mongo_master_enterprise_rhel_80_64_bit_dynamic_all_feature_flags_required_display_sharding_multiversion_patch_5c0652aac3cb161cb8d0bcf0d80cdbb084a74d0c_637be734e3c331777894bc9b_22_11_21_21_01_52',
...,
'metadata_links': [
{'url': 'https://evergreen.mongodb.com', 'text': 'evergreen', 'source': {'author': 'evergreen', …
```
> DAG-2538 Add metadata_links to TaskAnnotation.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
With the changes required for DAG-2570 we need this to be plain text now for use with the profiling build functionality.
> DAG-2570 Make get_patch_diff return plain text.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/task.py
- tests/evergreen/test_api.py
Based on the issue mentioned in [go/j/DAG-2619](http://go/j/DAG-2619) and [this slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1684853932503299) it was established that a task does not always have an associated manifest. This change makes it clear that it is optional and we can then use this change to handle the case in SPS.
I also created [EVG-19971](https://jira.mongodb.org/browse/EVG-19971) for Evergreen to not throw a 500 in this case.
> DAG-2619 Handled optionality of a task's manifest.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/stats.py
- tests/evergreen/data/task_stats.json
- tests/evergreen/test_stats.py
According to [DAG-2434](https://jira.mongodb.org/browse/DAG-2434) we need TaskStats to have `variant` and `num_total` attributes. Attribute `variant` was already there, so added just `num_total`.
> DAG-2434 Add 'num_total' attribute to TaskStats

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
Manifests changed from using 500 for not found cases to using 404. Updated the unit tests and ran locally to verify new handling.
``` python
>>> r = api.manifest_for_task("wiredtiger_ubuntu2004_perf_tests_bench_wt2853_perf_test_row_patch_f0dd370a81c108edaaebc0bbce29eb8e20fad
10c_646c48ac3e8e8621411becde_23_05_23_05_02_54")
>>> print(r)
None
```
> DAG-2624 Update handling of manifests for new error codes.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
To be used in SPS for the "start profiling build" button to allow us to enable profiling of builds that contain module changes. 
I have imported this locally to that repo and confirmed it is working, so once this is released I can put up the PR for changes in SPS.
> DAG-2824 Added patch_from_patch_id command.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
I opted to make the default for this True because we're using this in a lot of places already with the assumption that it's configured. 
Let me know if you feel differently.
> DAG-2860 Move logging configuration within constructor.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
change needed for [SERVER-81200](https://github.com/10gen/mongo/pull/15715) to enable `log_on_error` through `get_api` method
> SERVER-81200 added log on error in get_api class method

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/config.py
I've added a message that the evergreen file cannot be found when a user has set the flag to use it. The message also displays the locations of the configs
> DEVPROD-1575: added error for missing config file

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- src/evergreen/version.py
- tests/evergreen/test_api.py
This change is to support more flexibility when passing params when creating copies of versions. I have already used this new pattern in Signal Processing Service where these methods are called and verified they support the flexibility we need for setting params. After this change is merged and released I will have a PR ready for SPS with the new version of evergreen.py.
> DEVPROD-3964 Allow parameters to be passed when creating patches.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
https://jira.mongodb.org/browse/DEVPROD-4784
add caching support to the tasks_by_build method.
> DEVPROD-4784: Add caching support to tasks_by_build

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- src/evergreen/api.py
- tests/conftest.py
- tests/evergreen/test_api.py
In [DAG-527](https://jira.mongodb.org/browse/DAG-527) we made so that the EvergreenApi by default [establish a new HTTPS connection for every single Api call](https://github.com/evergreen-ci/evergreen.py/blob/9854bba6cb03c13f68e925e14225bda53c11ce23/src/evergreen/api.py#L112-L122). I realized that this is extremely inefficient , for instance the BuildBaron failure analyzer tool makes a lot of calls to the EVG Api during the setup phase that takes in average ~15 seconds in the setup phase. By re-using the same EVG Api session, the setup time goes down to 5 seconds.
I believe the changes in [DAG-527](https://jira.mongodb.org/browse/DAG-527) were motivated by the fact that in case of HTTP/network errors caused by an EVG application restart, the retries performed by the …
> DEVPROD-7415 Avoid HTTP connection storm on EvergreenAPI python client

- src/evergreen/api.py
- tests/evergreen/test_api.py
This is necessary in order to repeat a patch without adding extra variants.
> DEVPROD-4544: Add api for using --repeat-patch patch command.

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
JIRA Ticket: https://jira.mongodb.org/browse/DEVPROD-10470
Description:
We update the get_patch_diff function to now pass in a optional "module" parameter to the `_call_api` function. We also update the unit tests to test for this functionality.
> DEVPROD-10470 - Add module parameter to get_patch_diff

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- src/evergreen/api.py
https://github.com/evergreen-ci/evergreen.py/commit/1e6da7d96c4b404cb4aed55044eaf02ef9ca8607 makes use of the `backoff_max` in urllib3's `Retry`, introduced in urllib3==2.0.0. This project does not specify a restriction on the version of urllib3. Further complicating, many downstream projects that use this package explicitly require urllib3 < 2.0.0. This adds compatibility for both.
> Add compatibility for urllib3 versions < 2.0.0

- CHANGELOG.md
- pyproject.toml
- src/evergreen/api.py
- tests/evergreen/test_api.py
This call should be using the /permissions/users [route](https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage#tag/users/paths/~1permissions~1users/get) as opposed to the users/permissions [route](https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage#tag/users/paths/~1users~1%7Buser_id%7D~1permissions/get) (I recognize we made this confusing haha but alas)
Lmk if there's something I should do here for testing or etc
> DEVPROD-18380 fix evergreen route used for permissions for resource

- CHANGELOG.md
- README.md
- poetry.lock
- pyproject.toml
- Only support Python 3.9-3.13, the same versions we have testing for in waterfall
- Installing evergreen API from an unsupported Python version will fail fast ([negative testing after setting required python<=3.13](https://parsley.mongodb.com/evergreen/evergreen.py_cp313_evg_api_install_patch_6795e6a8664ebd298fa9a647d5e2b214151b63b8_689f6301c3e9fc000727defa_25_08_15_16_40_36/0/task?bookmarks=0,154&selectedLineRange=L143))
> DEVPROD-20931: Fix supported Python versions

- .evergreen.yml
- Strictly speaking we should wait for all `evg_api_install` tasks to succeed before publishing to PyPI.
- Once this PR is merged, publishing to pypi will fail because the same version already exists, which should be fine since no python code change here.
> DEVPROD-20931: Enforce publish dependency
